# Code Sentinel Configuration Example
# Copy this file to .sentinel.yml and customize for your project
#
# NOTE: All fields are OPTIONAL. Code Sentinel works with zero configuration.
# Only specify the settings you want to override.

# LLM Configuration (optional - auto-detected from action inputs)
llm:
  provider: openai  # openai | anthropic | gemini | ollama
  model: gpt-4o     # Provider-specific model
  # base_url: http://localhost:11434  # For Ollama only

# Review Focus Areas (optional)
review:
  # Review mode: 'quick' (single API call) or 'deep' (agentic with tools)
  # - quick: Cost-effective ~1 API call. Good for simple PRs.
  # - deep: More thorough, uses tools to explore codebase. ~3-10 API calls.
  mode: quick
  categories:
    - security      # OWASP top 10, secrets, injection
    - architecture  # SOLID, patterns, coupling
    - performance   # N+1, memory leaks, bundle size
    - bugs          # Logic errors, null checks, edge cases
    - best-practices
  min_severity: suggestion  # critical | warning | suggestion | nitpick
  skip_if_effort_below: 1   # 1-5 scale

# Files and authors to ignore (optional)
ignore:
  paths:
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "**/test/**"
    - "**/tests/**"
    - "**/__mocks__/**"
    - "**/__tests__/**"
    - "docs/**"
    - "*.md"
    - "package-lock.json"
    - "yarn.lock"
    - "pnpm-lock.yaml"
  authors:
    - dependabot[bot]
    - renovate[bot]
    - github-actions[bot]

# Custom instructions for the reviewer (optional)
# These are included in the prompt to guide the LLM
instructions:
  - "We use TypeScript strict mode"
  - "Prefer functional components with hooks in React"
  - "Always handle loading and error states"
  - "Use meaningful variable names, no abbreviations"

# Team patterns for consistency checks (optional)
patterns:
  - category: naming
    pattern: "Use camelCase for variables and functions, PascalCase for classes and components"
    examples:
      - "const userName = 'John'"
      - "class UserService {}"
  - category: architecture
    pattern: "Controllers should only call services, not repositories directly"
    examples:
      - "controller -> service -> repository"
  - category: testing
    pattern: "Use describe/it blocks with clear descriptions"
    examples:
      - "describe('UserService', () => { it('should create user', () => {}) })"
  - category: style
    pattern: "Prefer early returns to reduce nesting"

# Output configuration (optional)
output:
  summary: true
  inline_comments: true
  max_inline_comments: 15
  labels:
    enabled: true
    security_issue: "security"
    needs_review: "needs-review"
    effort_prefix: "effort:"  # Creates labels like "effort:3"

# AI Context Files (optional - provider-agnostic)
# Code Sentinel auto-searches for CLAUDE.md, AGENTS.md, COPILOT.md, etc.
context_files:
  enabled: true           # Enable context file loading
  search_defaults: true   # Search for standard AI convention files
  paths:                  # Additional custom paths (optional)
    - "team/CONVENTIONS.md"
    - ".ai/instructions.md"
